// packages/ui/components/Input.svelte
<script lang="ts">
  export let label = '';
  export let type = 'text';
  export let value = '';
  export let error = '';

  const typeAction = (node: HTMLInputElement) => {
    node.type = type;
  };
</script>

<div>
  <label>
    <span class="mb-1 block font-semibold">{label}</span>
    <input
      use:typeAction
      bind:value
      class="w-full rounded-md border border-zinc-300 bg-slate-50 py-2 px-2.5"
    />
  </label>
  {#if error}
    <div class="mt-1 text-sm text-red-600">{error}</div>
  {/if}
</div>

// apps/web/src/components/Input/Input.tsx
import type { FC } from 'react'
import type { FieldError, UseFormRegisterReturn } from 'react-hook-form'

type Props = {
  registerReturn: UseFormRegisterReturn
  fieldError: FieldError | undefined
  type: string
  label?: string
  placeholder?: string
  disabled?: boolean
}

export const Input: FC<Props> = ({
  registerReturn,
  fieldError,
  type,
  label,
  placeholder,
  disabled,
}) => {
  return (
    <div>
      <label>
        {label && (
          <span className="mb-2 block text-sm font-medium text-gray-900">
            {label}
          </span>
        )}
        <input
          type={type}
          className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500"
          placeholder={placeholder}
          disabled={disabled}
          {...registerReturn}
        />
      </label>
      {fieldError && (
        <p className="mt-2 text-sm text-red-600">{fieldError.message}</p>
      )}
    </div>
  )
}
