// apps/ui/components/button.tsx
import { MouseEventHandler, FC } from 'react'
import { classNames } from 'utils'

export type Props = {
  type?: 'submit' | 'button' | 'reset'
  primary?: boolean
  disabled?: boolean
  onClick?: MouseEventHandler<HTMLButtonElement>
}

export const Button: FC<Props> = ({
  type = 'button',
  primary,
  disabled,
  onClick,
  children,
}) => {
  return (
    <button
      type={type}
      className={classNames(
        'inline-flex items-center justify-center rounded-[20px] border border-transparent py-2 px-5 text-sm font-medium leading-[22px] shadow-sm focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
        primary
          ? 'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500'
          : 'bg-gray-100 hover:bg-gray-200 focus:ring-gray-300'
      )}
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
  )
}

// packages/ui/components/Button.svelte
<script>
  export let href = '';

  /** @type {'button' | 'reset' | 'submit'} */
  export let type = 'button';
  export let primary = false;
  export let blank = false;
  export let disabled = false;

  $: element = href ? 'a' : 'button';
  $: kindClass = primary
    ? 'border-zinc-900 bg-zinc-900 text-white hover:bg-zinc-700'
    : 'border-zinc-300 bg-slate-50 hover:border-zinc-400 hover:bg-slate-100';
  $: classAttrs = `inline-flex items-center justify-center space-x-1 rounded-md border px-5 py-2 text-sm duration-200 disabled:pointer-events-none disabled:opacity-40 ${kindClass}`;
  $: blankAttrs =
    href && blank
      ? {
          target: '_blank',
          rel: 'noopener noreferrer',
        }
      : {};
</script>

{#if element === 'a'}
  <a {...blankAttrs} class={classAttrs} {href}>
    <slot />
  </a>
{:else}
  <button {type} class={classAttrs} {disabled} on:click>
    <slot />
  </button>
{/if}
