// apps/web/src/lib/components/Button.svelte
<script lang="ts">
  import type { ButtonProps } from './types';

  let {
    children,
    href = '',
    type = 'button',
    primary = false,
    blank = false,
    disabled = false,
  } = $props<ButtonProps>();

  const element = $derived(href ? 'a' : 'button');
  const kindClass = $derived(
    primary
      ? 'border-zinc-900 bg-zinc-900 text-white hover:bg-zinc-700'
      : 'border-zinc-300 bg-slate-50 hover:border-zinc-400 hover:bg-slate-100',
  );
  const classAttrs = $derived(
    `inline-flex items-center justify-center space-x-1 rounded-md border px-5 py-2 text-sm duration-200 disabled:pointer-events-none disabled:opacity-40 ${kindClass}`,
  );
  const blankAttrs = $derived(
    href && blank
      ? {
          target: '_blank',
          rel: 'noopener noreferrer',
        }
      : {},
  );
</script>

{#if element === 'a'}
  <a {...blankAttrs} class={classAttrs} {href}>
    {@render children()}
  </a>
{:else}
  <button {type} class={classAttrs} {disabled} on:click>
    {@render children()}
  </button>
{/if}

// src/components/Button.tsx
import { MouseEventHandler, FC } from 'react'
import classnames from 'classnames'

interface Props {
  type?: 'submit' | 'button' | 'reset'
  primary?: boolean
  disabled?: boolean
  onClick?: MouseEventHandler<HTMLButtonElement>
  className?: string
}

const Button: FC<Props> = ({
  type = 'button',
  primary,
  disabled,
  onClick,
  className,
  children,
}) => {
  return (
    <button
      type={type}
      className={classnames(
        className,
        'inline-flex justify-center items-center py-[8px] px-[20px] border border-transparent shadow-sm rounded-[20px] text-sm leading-[22px] font-medium disabled:opacity-50 disabled:pointer-events-none focus:outline-none focus:ring-2 focus:ring-offset-2',
        {
          'text-white bg-red-600 hover:bg-red-700 focus:ring-red-500': primary,
          'bg-gray-100 hover:bg-gray-200 focus:ring-gray-300': !primary,
        }
      )}
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
  )
}

export default Button
